# -*- coding: utf-8 -*-
"""dida 325 final project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9FcTuHfB3NZrlP5Y42_y1gnAchUf7Jc

# **Gun-Related Mortality and Prevention**
Contributors: Lillian Pulaski, Gabriella Coleman, Melanie Nguyen, Renzo Guevarra

We are a team of analysts from a private firm who were contracted by the National Safety Council (NSC), an organization who is looking to expand their research and services towards gun-related issues, to analyze a comprehensive dataset from the CDC and other sources to uncover trends, identify at-risk populations, and recommend interventions. By combining our technical skills with a strong social justice lens, we aim to help NSC design strategies to reduce gun violence and save lives. Our diverse and intersectional identities within our team ensures that our analysis goes beyond the numbers, incorporating a deep understanding of the societal, cultural, and policy contexts behind the data.

This dataset includes data that FiveThirtyEight compiled from various sources; the CDC (Multiple Cause of Death Database), the FBI (police shootings), Mother Jones (mass shooting), and University of Maryland (Global Terrorism Database).

The columns in this dataset are all categoical by nature, with basic columns like year, month, sex, age, race, and education level. The columns intent and place provide information on the specific cause of death and where it occured. Police is a column with boolean variables (1 if shot by police, 0 if not shot by police). The hispanic column contains categorical codes which refer to the region the person is from based on the CDC's Hispanic Origin Code List:
 (https://www.cdc.gov/nchs/data/dvs/Appendix_D_Accessible_Hispanic_Origin_Code_List_Update_2011.pdf).
"""

#importing libraries to use for analysis

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

#loading in dataset

gun_deaths=pd.read_csv("https://raw.githubusercontent.com/fivethirtyeight/guns-data/refs/heads/master/full_data.csv")
gun_deaths=gun_deaths.drop(columns=['Unnamed: 0','place'])

#dropping extra index column and place column since they are irrelevant

#establishing color palette for following graphs
sns.set_style("darkgrid")
sns.color_palette("flare", as_cmap=True)

#checking if any data values are missing

gun_deaths.isna().sum()

"""The null values in this data are concentrated in the 'education' column. There are 100798 total rows of data, and 1422 rows with NAs in education. Since this is a small fraction of the data, we are dropping the rows that don't have data for the education column when it is relevant to the question."""

#preliminary look of data table

gun_deaths

"""## **Data Analysis**

Our four initial research questions we will be investigating will be comprehensive rather than specific so that by analyzing trends more generally, our team can deduce which certain demographics to investigate more in-depth (eg. certain demographics that show to be at more risk, most common intent across certain races, etc.). With our more specific questioning, we also strive to not exclude certain demographics that are known to be at higher risk and are typically ignored within data.

###**What are the trends in gun-related deaths over time (2012–2014), and how do they vary by intent (homicide, suicide, legal intervention, accidental)?**

We will use Pandas to manipulate the data and group it by year and intent. Matplotlib/Seaborn will be utilized to create line graphs, heatmaps, stacked bar charts, etc., to visualize trends in gun deaths by intent over the years.

Understanding trends over time can provide insights into how gun violence is evolving and whether certain types of incidents are becoming more or less common. Let's
"""

#grouping year, months, and intent to perform analysis on just these specific categories

yearly_trends = gun_deaths.groupby(['year', 'intent']).size().reset_index(name='count')

suicide_data = gun_deaths[(gun_deaths['intent'] == 'Suicide') & (gun_deaths['year'].isin([2012, 2013, 2014]))]
monthly_suicides = suicide_data.groupby(['year', 'month']).size().reset_index(name='count')

heatmap_data = yearly_trends.pivot(index ='intent', columns ='year', values ='count')

plt.figure(figsize=(8, 6))
sns.heatmap(heatmap_data, annot = True, fmt = 'd', cmap='flare')
plt.title('Gun-Related Deaths Heatmap (2012–2014)', fontsize=16)
plt.xlabel('Year', fontsize=14)
plt.ylabel('Intent', fontsize=14)
plt.show()

"""> ***fig. 3***

This heatmap illustrates that a significant portion of overall gun-related deaths is due to suicide, as shown by the dark purple. This is followed closely by homicide, as shown in the light purple. Because our overall goal is to see where we can reduce most gun-related deaths, our efforts are best directed towards those intents that pose the highest risk. That is not to say that accidental or undertermined causes of death are less important, yet with a limited dataset it is best that our team focuses on the causes that are most prominent.

Now let's visualize this in the form of a line graph to gain a better understanding of these two intent's relative relation to each other.
"""

suicide_homicide_data = yearly_trends[yearly_trends['intent'].isin(['Suicide', 'Homicide'])]

plt.figure(figsize = (10, 6))
sns.lineplot(data = suicide_homicide_data, x ='year', y ='count', hue ='intent', marker ='o', palette ='flare')
plt.title('Gun-Related Deaths: Suicide vs. Homicide (2012–2014)', fontsize=16)
plt.xlabel('Year', fontsize=14)
plt.ylabel('Number of Deaths', fontsize = 14)
plt.legend(title ='Intent', fontsize=12)
plt.xticks([2012, 2013, 2014])
plt.show()

"""> ***fig. 2***

This line graph further illustrates the data from the heatmap showing visually that suicides are significantly more prevalent than homicides, with a slight increase over the course of 2012 to 2014. Conversely, there was a slight decrease in homicides over the same year, and homicides in comparison to suicide are less of a cause but are still high enough in degree to warrant further analysis.

After having looked at the trend of intent by overall year, let's take a deeper look into how the trends of intents, specifically suicide and homicide, vary over the months per year.
"""

suicide_data = gun_deaths[(gun_deaths['intent'] == 'Suicide') & (gun_deaths['year'].isin([2012, 2013, 2014]))]
monthly_suicides = suicide_data.groupby(['year', 'month']).size().reset_index(name='count')

plt.figure(figsize=(10, 6))
sns.lineplot(data=monthly_suicides, x='month', y='count', hue='year', marker='o', palette='flare')
plt.title('Monthly Gun-Related Suicides (2012–2014)', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('Number of Suicides', fontsize=14)
plt.xticks(ticks=range(1, 13), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend(title='Year')
plt.grid(alpha=1)
plt.show()

""">***fig. 3***"""

homicide_data = gun_deaths[(gun_deaths['intent'] == 'Homicide') & (gun_deaths['year'].isin([2012, 2013, 2014]))]
monthly_homicides = homicide_data.groupby(['year', 'month']).size().reset_index(name='count')

plt.figure(figsize=(10, 6))
sns.lineplot(data=monthly_homicides, x='month', y='count', hue='year', marker='o', palette='flare')
plt.title('Monthly Gun-Related Homicides (2012–2014)', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('Number of Homicides', fontsize=14)
plt.xticks(ticks=range(1, 13), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun','Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend(title='Year')
plt.grid(alpha=1)
plt.show()

"""> ***fig. 4***

## Month-Based Analysis

The trends obvserved in the graphs of gun-related suicides and homicides show common patterns in both categories, with a noticeable decline in January to February followed by an increase during the spring and summer months.

For suicides, the number peaks around March to May, with a noticeable increase in September 2014 compared to the declining trend in previous years. This seasonal uptick in suicides during the spring could be attributed to the stress of academic pressures, but a further analysis looking into age ranges for suicides could provide a clearer picture on this connection. The lower rates of suicide in January and February could be linked to the end of the holiday season, a time when many people may feel relief after the emotional strain of the holidays. While many believe that suicide is heightened during the holiday season, this appears to not be the case as there is a noticeable decline in November to December for suicides for all three years. Research done on suicide (2012) by the CDC highlights this falsely believed phenomenom, and explores reasons as to why this is as well as the reason for an increase during the warmer months:

- "Suicides were actually most numerous during the late spring and summer months of May, June, July, and August. May appears to be the month with the highest incidence of suicide. May was among the top 3 months for suicide during all 12 years. June was listed in the top 3 for 3 out of 12 years, July for 8 out of 10 years, and August for 6 out of 12 years. Criminologists and psychologists have followed this phenomenon for decades, and argue that high temperatures may increase discomfort and facilitate disinhibition, aggression and violence, generating an increase in suicidal acts (Anderson, 1989; Kim, Y., Kim, H., & Kim, D., 2011; Page, L., Hajat, S. & Kovats, S. R., 2007)."

source: https://blogs.cdc.gov/nchs/2014/01/10/1121/

In terms of homicide, a noticeable increase can be seen in December, which may be associated with the pressures of the holiday season, including relationship issues, financial strain, and substance abuse. The decline in January and February could be due to colder weather, discouraging outdoor activity and subsequently reducing opportunities for violence and homicide. However, there is a substantial increase in homicides during the following spring, peaking in the summer months, particularly from June to August. This could be explained by warmer weather encouraging people to spend more time outdoors, increasing the opportunities for social interaction and subsequently opportunities for homicide. In areas most prone to gun violence, ie, impoverished and urban areas, this outdoor socialization may contribute to heightened tensions.

# Demographic Analysis

## **How do gun-related deaths differ across different demographic groups (age, sex, race, etc.)?**

We utilized Pandas to group data by demographics to calculate and compare the number of deaths in each category. We used Seaborn to create bar plots and heatmaps to visualize the demographic breakdown of gun deaths. Understanding how gun deaths affect various demographic groups differently can highlight specific communities at higher risk and from there more in-depth analysis can be made. Targeted interventions and policies from further analysis can then be subsequently implemented.
"""

#seperating into groups
bins = [0,17,24,34,44,54,64,74,84,100]
labels = ["0-17","18-24","25-34","35-44", "45-54", "55-64", "65-74", "75-84", "85+"]

gun_deaths['age_group'] = pd.cut(gun_deaths['age'], bins=bins, labels=labels, right=False)
#deaths per age group
age_death = gun_deaths["age_group"].value_counts().sort_index().reset_index()
age_death.columns = ["age_group", "death_count"]


plt.figure(figsize=(10,6))
sns.barplot(age_death, x='age_group', y='death_count', palette = "flare")
plt.title('Gun Deaths by Age Group', fontsize=16)
plt.xlabel('Age Group')
plt.ylabel('Number of Gun Deaths')
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

"""> ***fig. 5***

The chart above illustrates the distribution of gun-related deaths across various age groups. The highest number of deaths occurred among individuals aged 25–34, followed closely by those in the 18–24, 35–44, 45–54, and 55–64 age brackets, which all show similar death counts. Deaths significantly decline in both the youngest (0–17) and oldest (75+) age groups. This distribution suggests that young to middle-aged adults are disproportionately affected by gun violence, highlighting a critical demographic for targeted prevention efforts.
"""

# Count deaths per sex
sex_deaths = gun_deaths['sex'].value_counts().reset_index()
sex_deaths.columns = ['sex', 'death_count']

# Plot

custom_palette = {'M': '#1f77b4',
                  'F': '#ff69b4'}
plt.figure(figsize=(6,4))
sns.barplot(x='sex', y='death_count', data=sex_deaths, palette='flare_r')
plt.title('Gun Deaths by Sex', fontsize=16)
plt.xlabel('Sex')
plt.ylabel('Number of Gun Deaths')
plt.tight_layout()
plt.show()

"""> ***fig. 6***

This bar chart shows a stark disparity in gun-related deaths between sexes. Men account for the vast majority of gun deaths, with numbers exceeding 80,000, while women represent just under 20,000 deaths. This significant difference highlights the disproportionate impact of gun violence on men, suggesting a need for gender-specific interventions and policies.
"""

# Count deaths per race
race_deaths = gun_deaths['race'].value_counts().reset_index()
race_deaths.columns = ['race', 'death_count']

# Plot
plt.figure(figsize=(10,6))
sns.barplot(x='race', y='death_count', data=race_deaths, palette="flare_r")
plt.title('Gun Deaths by Race', fontsize=16)
plt.xlabel('Race')
plt.ylabel('Number of Gun Deaths')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""> ***fig. 7***

This bar chart illustrates the distribution of gun-related deaths across different racial groups. The White population experiences the highest number of gun deaths, followed by the Black population, then Hispanic. Asian and Native American groups represent smaller shares of gun deaths in comparison. These results highlight the varying impact of gun violence across racial communities, indicating the importance of tailored approaches for addressing gun-related harm in different populations.
"""

# Group by age group and race, and count
age_race = gun_deaths.groupby(['age_group', 'race']).size().unstack(fill_value=0)
age_race = age_race.reindex(index=age_race.index[::-1])


# Plot heatmap
plt.figure(figsize=(12,8))
sns.heatmap(age_race, annot=True, fmt='d', cmap='flare_r')

plt.title('Gun Deaths by Age Group and Race', fontsize=18)
plt.xlabel('Race')
plt.ylabel('Age Group')
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""> ***fig. 8***

This heatmap visualizes the intersection of age groups and racial categories in gun-related deaths. It reveals that certain age groups, particularly those in middle adulthood, experience higher rates of gun deaths across multiple racial categories. The White population shows a noticeable concentration of gun deaths across various age groups, particularly in the middle-aged brackets.
The heatmap also highlights racial disparities, with the Black population experiencing significant gun violence in the young adult and middle-aged age groups. Smaller groups, such as Asian and Native American, represent fewer deaths overall, with patterns that differ from the larger racial groups.
This visualization underscores the need to consider both age and race when addressing gun violence, as interventions may need to be tailored to the specific needs of different demographic intersections.
"""

# Filter for White individuals aged 45–64
target_group = gun_deaths[
    (gun_deaths['race'] == 'White') &
    (gun_deaths['age_group'].isin(['45-54', '55-64']))
]

# Group by sex and intent to count number of deaths
grouped = target_group.groupby(['sex', 'intent']).size().reset_index(name='death_count')

# Plotting
plt.figure(figsize=(10, 6))
sns.barplot(data=grouped, x='intent', y='death_count', hue='sex', palette='flare')
plt.title('Gun Deaths by Intent and Sex (White, Ages 45–64)', fontsize=14)
plt.xlabel('Type of Incident')
plt.ylabel('Number of Deaths')
plt.legend(title='Sex')
plt.tight_layout()
plt.show()

"""> ***fig. 9***

This graph breaks down gun deaths by intent for White individuals aged 45-64. The largest cause of death in this demographic is suicide, with men significantly outnumbering women. Homicide is the second leading cause, with men’s deaths roughly double those of women. This specific demographic was chosen for analysis due to its relatively higher rates of gun-related deaths in middle adulthood, particularly in terms of suicide. Understanding the underlying causes of gun violence in this group is crucial for identifying targeted mental health and violence prevention strategies for middle-aged adults.

There could be multiple potential reasons as to why this specific demographic resort to gun-induced suicide, but all would most likely be linked to significant life stressors. According to a study done by SSM Health, they find that "serious life stressors such as intimate partner problems, legal issues, unemployment/financial problems and health concerns are among the most common precipitating circumstances for suicides in middle-aged men" (SSM Health). This could be further exacerbated by societal expectations of men having to be strong in the face of difficulties, resulting in untreated mental health issues and thus leaving them vulnerable to suicide.

(source: https://www.ssmhealth.com/newsroom/blogs/ssm-health-matters/october-2019/middle-aged-men-more-likely-to-die-by-suicide)
"""

# Filter for Black individuals aged 18-34
target_group_black = gun_deaths[
    (gun_deaths['race'] == 'Black') &
    (gun_deaths['age_group'].isin(['18-24', '25-34']))
]

# Group by sex and intent to count number of deaths
grouped_black = target_group_black.groupby(['sex', 'intent']).size().reset_index(name='death_count')

# Plotting
plt.figure(figsize=(10, 6))
sns.barplot(data=grouped_black, x='intent', y='death_count', hue='sex', palette='flare')
plt.title('Gun Deaths by Intent and Sex (Black, Ages 18–34)', fontsize=14)
plt.xlabel('Type of Incident')
plt.ylabel('Number of Deaths')
plt.legend(title='Sex')
plt.tight_layout()
plt.show()

"""> ***fig. 10***

This graph focuses on gun deaths among Black individuals aged 18–34, broken down by intent and sex. This demographic was chosen because it had the highest number of gun deaths within the Black population. The results show that homicide is the leading cause of gun-related deaths for this group, with a notably higher rate among men compared to women. Suicide, while present, accounts for a much smaller proportion. The clear disparity highlights the importance of addressing the underlying social and economic factors contributing to violent deaths in young Black communities.

# Correlation & Effects of Education Level

###**What is the relationship between education level and gun-related deaths?**

For this analysis, we used Pandas to group data by education level and count the number of deaths in each group, and Seaborn to explore how the distribution of gun-related deaths varies across different education levels. Research often shows that education level can correlate with various social outcomes, including gun-violence, criminal activity, and increased mental health issues. By analyzing this relationship, we can explore whether lower education levels are associated with higher rates of gun-related deaths.
"""

#new_order = ["Less than HS", "HS/GED", "Some college", "BA+"]
#grouped_edu = gun_deaths.groupby(["education", "intent"]).size().reset_index(name="count")
#grouped_edu = grouped_edu[new_order]

sns.countplot(gun_deaths, x = "education", hue = "intent", palette='flare_r')
plt.xlabel("Education Level")
plt.ylabel("Number of Gun-Related Deaths")
plt.title("Gun-Related Deaths by Education Level")

plt.show()

"""> ***fig. 11***

Our data shows us that people with Less than HS education experience a low amount of gun-related deaths overall. This may be attributed to this education level mostly containing children. The number of deaths spikes up dramatically once a HS/GED education is reached, then declines as education level increases. Finally, the lowest rate of gun-related deaths is reached at the highest level of education, which is BA+.

There are several things this data can tell us. The only education level at which there is more homicide than suicide is "Less than HS." As education level increases, the ratio of homicides to suicides decreases. This may suggest that as educational level increases, severe interpersonal conflicts decrease, which leads to a decrease in homicide.

What's interesting, however, is how many gun-related deaths involve someone with an HS/GED diploma. Could aiding individuals in their journey for educational attainment be one method to reducing gun-related deaths?

# Predictive Anaylsis

### **Can we predict the likelihood of a gun-related death being classified as suicide or homicide based on demographic and characteristics (sex, race, education level)?**

For this analysis, Logistic Regression is used to predict whether an incident is more likely to be a suicide based on features like sex, age, race, education level, etc. Pandas is utilized for data manipulation, and Seaborn for data visualization. Predicting what factors tend to be associated with a gun death being classified as a suicide based on available data can help in designing early intervention strategies. The results of the model can show what demographics and groups policy makers should be targeting to prevent suicides by firearms.
While we don't have any regional data so far, merging geographical locations of gun-related deaths can be of immense help in implementing strategies in particular areas throughout the United States.
"""

#creating modified dataset specifically for predictive analysis (dropping null value rows for education and intent)

gun_deaths2=gun_deaths.copy()
gun_deaths2=gun_deaths4.dropna(subset=['education','intent'])


gun_deaths4.isna().sum()

#define features (X) variable

X=gun_deaths2[['sex', 'race', 'education']] #features using to predict intent
X=pd.get_dummies(X, drop_first=True).astype("float32")

X.head()

#define outcome (y) variable

y=(gun_deaths2['intent'] == 'Suicide').astype(int) #outcome is if intent was classified as suicide (1)

y.value_counts()

#creating logistic regression model

X=sm.tools.tools.add_constant(X)

model=sm.Logit(y, X).fit(maxiter=100) #model will run more iterations

print(model.summary())

#show 10 predictions produced by the model

phat=model.predict()
phat[0:10]

"""The values range between 0.5161 and 0.9295, meaning the lowest probability is a 51.61% chance and the highest is a 92.95% chance of a gun death being classified as a suicide."""

confusion=model.pred_table(threshold=0.5) #errors at 95% confidence
confusion

confusion.trace()/confusion.sum()*100

"""The gun suicide death model has 82.14% model accuracy at a 95% confidence interval."""

#producing a visualization for feature importance using coefficients produced by the model

features=['race_White', 'race_Black', 'education_Less than HS', 'education_HS/GED',
            'sex_M', 'race_Hispanic', 'education_Some college', 'race_Native American/Native Alaskan']

abs_coefficients=[1.5570,-1.8083,-1.4247,-0.9417,0.7050, -0.5320, -0.5114, 0.4679]

#creating a dataframe with model's output
importance_df=pd.DataFrame({
    'Feature': features,
    'Absolute Importance': abs_coefficients})

importance_df=importance_df.sort_values('Absolute Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Absolute Importance', y='Feature', data=importance_df, hue='Feature', palette='flare', legend=False)

plt.title('Feature Importance for Predicting Likelihood of Gun Death Being A Suicide', fontsize=14)
plt.xlabel('Absolute Coefficient Value', fontsize=12)
plt.ylabel('Feature', fontsize=12)

plt.show()

"""> ***fig. 12***

The model shows a pseudo R-squared value of 0.3503, indicating okay predictive power for gun suicides.
Regarding demographic factors, Black and Hispanic people have significant negative coefficients, indicating they are less at risk of gun suicide. Looking at significant positive coefficients, being male, Native American, or white are risk factors, with white individuals showing the strongest effect. To prevent or lower gun suicides, we should focus on white males.
For education, higher education levels are associated with greater likelihood of dying by suicide. This might suggest the need to focus prevention efforts on people working in higher-level jobs where stress could be a contributing factor.
"""

#repeating the same model except using the intent homicide as the outcome variable

X=gun_deaths4[['sex', 'race', 'education']]
X=pd.get_dummies(X, drop_first=True).astype("float32")

y=(gun_deaths4['intent'] =='Homicide').astype(int)

X=sm.tools.tools.add_constant(X)

model2=sm.Logit(y, X).fit(maxiter=100)

print(model2.summary())

phat=model2.predict()
phat[0:10]

"""The values range between 0.055 and 0.432, meaning the lowest probability is a 5.5% chance and the highest is a 43.2% chance of a gun death being classified as a homicide."""

confusion=model2.pred_table(threshold=0.5) #errors at 95% confidence
confusion

confusion.trace()/confusion.sum()*100

"""The gun homicide death model has 83.48% model accuracy at a 95% confidence interval."""

features = ['race_White', 'race_Black', 'education_Less than HS', 'education_HS/GED',
            'sex_M', 'race_Hispanic', 'education_Some college', 'race_Native American/Native Alaskan']

abs_coefficients = [-1.7027, 1.7285, 1.4280, 1.0071, -0.7414, 0.4990, 0.5399, -0.5716]

importance_df = pd.DataFrame({
    'Feature': features,
    'Absolute Importance': abs_coefficients})

importance_df = importance_df.sort_values('Absolute Importance', ascending=False)

plt.figure(figsize=(10, 6))
ax = sns.barplot(x='Absolute Importance', y='Feature', data=importance_df, hue='Feature', palette='flare_r', legend=False)

plt.title('Feature Importance for Predicting Likelihood of Gun Death Being A Homicide', fontsize=14)
plt.xlabel('Absolute Coefficient Value', fontsize=12)
plt.ylabel('Feature', fontsize=12)

plt.show()

"""> ***fig. 13***

The model shows a pseudo R-squared value of 0.3439, indicating okay predictive power for gun suicides. The data suggests that individuals with low education levels and Black individuals are at a higher risk to be victims of a gun homicide, while white males are at a lower risk. This suggests that in order to lower gun homicide rates, the groups that need to be protected are Black individuals and lower educated people.

## **Policy Recommendations**

One focus that should be implemented after careful analysis should undoubtedly center on providing mental health services for at-risk populations, most notably targeting middle-aged white males. Given the significantly higher suicide rates among this particular demographic, interventions should focus on providing mental health support, especially in high stress environments such as in work and career, or relationship/family stressors. Additionally, dismantling stigma around mental health, particulary for men who grow up in a society where ideals of masculinity influence behaviors and norms, is critical. Men need to understand that asking for help is not a sign of weakness or failure, but instead is encouraged and healthy, and this sentiment can be dispersed by use of nationwide public health awareness campaigns.

Another recommendation to reduce gun-related mortality is by advocating for stricter gun control laws and purchasing restrictions. There is little regulation in allowing who or who cannot purchase guns, and while this issue is enshrouded in deep political discourse, the NSC can aid in the on-going nationwide effort to instill stricter and safer regulations for gun purchasing. The organization should advocate for stricter background checks and waiting periods for gun purchases, particularly for individuals with a history of mental health issues or those who have shown signs of suicide ideation. This would help prevent at-risk individuals from purchasing guns impulsively. However, due to guns already being so common within the American household, many men who perhaps have not had thoughts of suicide could easily resort to it with easy gun access. Therefore, the organization could also advocate for annual background checks and continuous mental health assessment for current gun owners as well. With advocating for increased gun regulations to ensure safety for both the individual and general population, as well as nationwide mental health awareness campaigns with an emphasis on targeting middle aged white men, the NSC can take steps in reducing suicide for this at-risk population.

Another area that needs to be addressed after our analysis are black communities who face socioeconomic disparities. Black communities are disproportionately affected by gun-related homicides and gang violence. While the issues inflicted by system racism are extremely complex and require more than just policy recommendations, the NSC could focus their effort towards tackling specific aspects of this issue, one being education. As we have seen in our analysis, homicides seem to affect black men who only achieve high school level of education/GED, or lesser. From this, the NSC should invest in educational initiatives and mentorship programs that focus on black men in these disadvantaged communities. By synthesizing several data tables together, we can conclude that a large proportion of homicide victims are young black men from ages 18-34 who don't go on to higher education or fail to finish high school. (fig. 10, fig. 11, fig. 13). If the NSC can advocate for educational and mentorship initiatives that target black men younger than 18, we can hope to mitigate or lessen the potential of these at-risk individuals to become victims of homicide and reduce the appeal of gang involvement and provide alternatives to violence. While it is critical for young men to have good role models and support system in order to lift themselves out of the issues that systemic racism has caused, it should not be their responsibility entirely. Tackling the issues of system racism requires a sensitive and intentional look at data from data scientists and analysts so that these disadvantaged communities no longer go overlooked.

Another observation that should be addressed is the consistent uptick in suicides and homicides during the warmer months/spring & summer seasons. Given this particular annual increase, the NSC should also develop targeted interventions to circumvent the risks that arise due to higher temperatures and warmer weather, which can increase irritation and opportunities for gun violence since more people are spending time outside. We recommend the NSC advocate for implementing community events and recreational activity during the warmer months/when people have more free time to provide alternatives for at-risk individuals. Additionally, while mental health awareness should be emphasized all year long, public health campaigns could be increased during these time frames as to make people more aware, especially in environments where stress is high such as in work and career. Companies, firms, and general areas of employment can start implementing mental health awareness during the warmer months when agitation is high and the stress of work accumulates, as to make employees feel heard, seen, and understood, making sure they know they have support.

## **Suggestions for Further Research**

Naturally, due to general population distribution, the dataset accounts primarily for white men, followed by black men. But just because these demographics account for a higher number of datapoints, that does not mean we should turn a blind eye to other marginalized groups that are still heavily affected by gun-related mortality. For instance, as illustrated in fig. 12, we see that while coefficients "race_White" and "sex_M" account for a high number of suicides (perhaps due to just a large population), Native American/Native Alaskan is the third most signicant coefficient in predicting suicides, despite representing a small percent of the overall US population. American Indians and Alaska Natives are some of the most overlooked communities in the US, subjected to multitiudes of societal issues stemming from centuries of systemic racism and colonization. According to the CDC, "American Indian and Alaska Native people are at higher risk of dying by suicide compared with other Americans. In 2022, non-Hispanic AI/AN people had a suicide rate 91% greater than the general population" (https://www.cdc.gov/suicide/programs/tribal.html). So while our analysis primarily targeted white, middle-aged men in terms of suicide prevention, efforts and further research should also be directed towards Native American/Alaska Native communites. This is an instance where looking beyond the numbers is absolutely critical if we wish to address issues that affect not just dominantly researched groups but marginalized groups as well. We recommend further research on gun-mortality, especially suicide, be carried out solely on Native American/Alaska Native communities.

Other recommendations for future research on this topic is to expand the data, including information such as geographical location/state/city. If geographical data is incorporated, we could utilize data visualization with geopandas to gain an understanding of exactly where these preventitive measures and policies should be implemented.

Incorporating more years for analysis to gain a bigger picture of general long trends in gun-mortality would be greatly beneficial as well. While a general analysis can be drawn from the years we analyzed (2012-2014), future research should be done having incorporated years ranging even further back before 2012, up to the current past year (2024), as to observe decade-long trends more comprehensively and thus provide even more in-depth solutions.

# **Final Words**

Thank you for taking the time to read and reflect on our team's research on gun-related mortality, using data from FiveThirtyEight compiled from various sources. In collaboration with NSC, we hope to have provided preliminary yet substantive analysis on gun-related deaths. While this is a comprehensive and complex issue that will take time to fix, taking steps in advocating for safer gun control regulations, focusing on commmunity-driven efforts and educational/mentorship initiatives, and destigmatizing mental health problems are critical if we wish to save lives.



For any further questions, please reach out to

dataforjustice@gmail.com

or contact **607-777-2000.**

*By Lillian Pulaski, Gabriella Coleman, Melanie Nguyen, Renzo Guevarra*
"""